name: build

on: [push]

jobs:
  build-and-test:
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_trf

      - name: Run black
        shell: bash
        run: pre-commit run black --all-files

      - name: Run flake8
        shell: bash
        run: pre-commit run flake8 --all-files

      - name: Run docformatter
        shell: bash
        run: pre-commit run docformatter --all-files

      - name: Run pydocstyle
        shell: bash
        run: pre-commit run pydocstyle --all-files

      - name: Run mypy
        shell: bash
        run: pre-commit run mypy --all-files
   
      - name: Run pytest with code coverage
        run: |
          pytest --junitxml pytest.xml --cov=. --cov-report=term-missing --cov-report=xml --cov-branch | tee pytest-coverage.txt